services:
  - type: web
    name: taskflow-pro
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm run start
    plan: free
    envVars:
      - key: DATABASE_URL
        value: file:./prod.db
      - key: AUTH_TRUST_HOST
        value: "true"
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: AUTH_SECRET
        generateValue: true
